"""adicionando status ao pedido

Revision ID: 13139bae374a
Revises: a6391238fe12
Create Date: 2026-05-22 16:35:24.217700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13139bae374a'
down_revision: Union[str, Sequence[str], None] = 'a6391238fe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos') as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
